version: '2'
services:
  php:
    build:  ./docker/php
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
#     volumes_from:
#       - datastore
#   datastore:
#     image: busybox
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres:
